name: Lint
on: push

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup Python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Setup dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: flake8 .
      - name: Format
        run: black --verbose --diff .
